# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79929e3c8e8d6820d735b8f21827b0b2b2600860a6bc2955c2631eae559470bb967dea5a543333efe15d6206137c20e369329e6339fec0c2d34a0759d2de5be1

test:
  secret_key_base: e3670dc83d37e623432021e91c2108af00ba12858d958d1f7e08620044d87fe4b0b623fd48aa1f3bcdd74bd04da9bdbdfc24777c9a99353b144b9aefed272b3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
